service:
  name: user_server
  port: 9091
  weight: 1

#port: 10666
BackendService:
  #localhost db
  host: db
  port: 3306
  user: root
  password: 1234
  db: GoWeb

etcd:
  endpoints:
    - "etcd_server:2379"
    #etcd_server localhost