service:
  name: blog.RouterService #这个name只跟etcd注册里的服务名有关
  port: 9092
  weight: 1

Backends:
  BlogService: blog.BlogService
  UserService: blog.UserService

#port: 10666
#BackendService:
  #localhost db


etcd:
  endpoints:
    - "localhost:2379"
    #etcd_server localhost