service:
  name: blog.UserService
  port: 9091
  weight: 1

#port: 10666
mysql:
  #localhost db
  host: localhost
  port: 3306
  user: root
  password: 1234
  db: GoWeb

etcd:
  endpoints:
    - "localhost:2379"
    #etcd_server localhost